
spring:
  datasource:
    url: jdbc:mysql://ren2u.cfoukd3jcnhj.ap-northeast-2.rds.amazonaws.com:3306/rentserver
    username: admin
    password: ajouparan2022-2
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace