spring:
    datasource:
        # url: jdbc:mysql://ren2u.cfoukd3jcnhj.ap-northeast-2.rds.amazonaws.com:3306/rentserver
        url: jdbc:mysql://ren2u.cfoukd3jcnhj.ap-northeast-2.rds.amazonaws.com:3306/test_haechan
        username: admin
        password: ajouparan2022-2
        driver-class-name: com.mysql.jdbc.Driver
